
clean:
	rm -rf ./bin

run:
	javac -encoding UTF-8 -d ./bin \
		./src/MainApp.java \
		./src/Alumno.java \
		./src/Reader.java \
		./src/Writer.java \
		./src/XMLReader.java \
		./src/XMLWriter.java \
		./src/SAXWriter.java \
		./src/SAXReader.java \
		./src/SAXHandler.java \
		./src/DOMWriter.java \
		./src/DOMReader.java
	java -cp ./bin MainApp