clean:
	rm -rf ./bin

run:
	javac -encoding UTF-8 -d ./bin \
		./src/Everest_carlos_pomares.java \
		./src/Cima.java \
		./src/Escalador.java \
		./src/Helicoptero.java
	java -cp ./bin Everest_carlos_pomares